# string
title = "test string title"

# bool (note: 小写)
debug = true
verbose = false

# num
port = 8080
timeout = 30.5

# array
array1 = ["string1", "string2"]
array2 = [10, 20, 30]

# map
[map1]
item1 = "map1 string"
item2 = 1
item3 = true

[map1.sub1]
item1 = "map1 sub1 string"
item2 = 11
item3 = true

[map1.sub2]
item1 = "map1 sub2 string"
item2 = 21
item3 = true

[serial]
